/** Name / mascot / alias → official abbrev for NHL/NBA/MLB/MLS Odds rows.
 * Unique keys only (drops "new york", "chicago", "los angeles" collisions).
 * Keep in sync with src/features/lounge/*TeamCatalog.generated.js.
 */
const NHL_NAME_ABBREV: Record<string, string> = {
  'ana': 'ANA',
  'anaheim': 'ANA',
  'anaheim ducks': 'ANA',
  'ducks': 'ANA',
  'bos': 'BOS',
  'boston': 'BOS',
  'boston bruins': 'BOS',
  'bruins': 'BOS',
  'buf': 'BUF',
  'buffalo': 'BUF',
  'buffalo sabres': 'BUF',
  'sabres': 'BUF',
  'car': 'CAR',
  'carolina': 'CAR',
  'carolina hurricanes': 'CAR',
  'hurricanes': 'CAR',
  'blue jackets': 'CBJ',
  'cbj': 'CBJ',
  'columbus': 'CBJ',
  'columbus blue jackets': 'CBJ',
  'calgary': 'CGY',
  'calgary flames': 'CGY',
  'cgy': 'CGY',
  'flames': 'CGY',
  'blackhawks': 'CHI',
  'chi': 'CHI',
  'chicago': 'CHI',
  'chicago blackhawks': 'CHI',
  'avalanche': 'COL',
  'col': 'COL',
  'colorado': 'COL',
  'colorado avalanche': 'COL',
  'dal': 'DAL',
  'dallas': 'DAL',
  'dallas stars': 'DAL',
  'stars': 'DAL',
  'det': 'DET',
  'detroit': 'DET',
  'detroit red wings': 'DET',
  'red wings': 'DET',
  'edm': 'EDM',
  'edmonton': 'EDM',
  'edmonton oilers': 'EDM',
  'oilers': 'EDM',
  'fla': 'FLA',
  'florida': 'FLA',
  'florida panthers': 'FLA',
  'panthers': 'FLA',
  'kings': 'LA',
  'la': 'LA',
  'lak': 'LA',
  'los angeles': 'LA',
  'los angeles kings': 'LA',
  'min': 'MIN',
  'minnesota': 'MIN',
  'minnesota wild': 'MIN',
  'wild': 'MIN',
  'canadiens': 'MTL',
  'mon': 'MTL',
  'montreal': 'MTL',
  'montreal canadiens': 'MTL',
  'mtl': 'MTL',
  'devils': 'NJ',
  'new jersey': 'NJ',
  'new jersey devils': 'NJ',
  'nj': 'NJ',
  'njd': 'NJ',
  'nashville': 'NSH',
  'nashville predators': 'NSH',
  'nsh': 'NSH',
  'predators': 'NSH',
  'islanders': 'NYI',
  'new york islanders': 'NYI',
  'nyi': 'NYI',
  'new york rangers': 'NYR',
  'nyr': 'NYR',
  'rangers': 'NYR',
  'ott': 'OTT',
  'ottawa': 'OTT',
  'ottawa senators': 'OTT',
  'senators': 'OTT',
  'flyers': 'PHI',
  'phi': 'PHI',
  'philadelphia': 'PHI',
  'philadelphia flyers': 'PHI',
  'penguins': 'PIT',
  'pit': 'PIT',
  'pittsburgh': 'PIT',
  'pittsburgh penguins': 'PIT',
  'kraken': 'SEA',
  'sea': 'SEA',
  'seattle': 'SEA',
  'seattle kraken': 'SEA',
  'san jose': 'SJ',
  'san jose sharks': 'SJ',
  'sharks': 'SJ',
  'sj': 'SJ',
  'sjs': 'SJ',
  'blues': 'STL',
  'st louis': 'STL',
  'st louis blues': 'STL',
  'stl': 'STL',
  'lightning': 'TB',
  'tampa bay': 'TB',
  'tampa bay lightning': 'TB',
  'tb': 'TB',
  'tbl': 'TB',
  'maple leafs': 'TOR',
  'tor': 'TOR',
  'toronto': 'TOR',
  'toronto maple leafs': 'TOR',
  'ari': 'UTAH',
  'arz': 'UTAH',
  'mammoth': 'UTAH',
  'utah': 'UTAH',
  'utah mammoth': 'UTAH',
  'canucks': 'VAN',
  'van': 'VAN',
  'vancouver': 'VAN',
  'vancouver canucks': 'VAN',
  'golden knights': 'VGK',
  'veg': 'VGK',
  'vegas': 'VGK',
  'vegas golden knights': 'VGK',
  'vgk': 'VGK',
  'jets': 'WPG',
  'winnipeg': 'WPG',
  'winnipeg jets': 'WPG',
  'wpg': 'WPG',
  'capitals': 'WSH',
  'was': 'WSH',
  'washington': 'WSH',
  'washington capitals': 'WSH',
  'wsh': 'WSH',
}

const NBA_NAME_ABBREV: Record<string, string> = {
  'atl': 'ATL',
  'atlanta': 'ATL',
  'atlanta hawks': 'ATL',
  'hawks': 'ATL',
  'bkn': 'BKN',
  'brk': 'BKN',
  'brooklyn': 'BKN',
  'brooklyn nets': 'BKN',
  'nets': 'BKN',
  'bos': 'BOS',
  'boston': 'BOS',
  'boston celtics': 'BOS',
  'celtics': 'BOS',
  'cha': 'CHA',
  'charlotte': 'CHA',
  'charlotte hornets': 'CHA',
  'cho': 'CHA',
  'hornets': 'CHA',
  'bulls': 'CHI',
  'chi': 'CHI',
  'chicago': 'CHI',
  'chicago bulls': 'CHI',
  'cavaliers': 'CLE',
  'cle': 'CLE',
  'cleveland': 'CLE',
  'cleveland cavaliers': 'CLE',
  'dal': 'DAL',
  'dallas': 'DAL',
  'dallas mavericks': 'DAL',
  'mavericks': 'DAL',
  'den': 'DEN',
  'denver': 'DEN',
  'denver nuggets': 'DEN',
  'nuggets': 'DEN',
  'det': 'DET',
  'detroit': 'DET',
  'detroit pistons': 'DET',
  'pistons': 'DET',
  'golden state': 'GS',
  'golden state warriors': 'GS',
  'gs': 'GS',
  'gsw': 'GS',
  'warriors': 'GS',
  'hou': 'HOU',
  'houston': 'HOU',
  'houston rockets': 'HOU',
  'rockets': 'HOU',
  'ind': 'IND',
  'indiana': 'IND',
  'indiana pacers': 'IND',
  'pacers': 'IND',
  'clippers': 'LAC',
  'la': 'LAC',
  'la clippers': 'LAC',
  'lac': 'LAC',
  'lakers': 'LAL',
  'lal': 'LAL',
  'los angeles': 'LAL',
  'los angeles lakers': 'LAL',
  'grizzlies': 'MEM',
  'mem': 'MEM',
  'memphis': 'MEM',
  'memphis grizzlies': 'MEM',
  'heat': 'MIA',
  'mia': 'MIA',
  'miami': 'MIA',
  'miami heat': 'MIA',
  'bucks': 'MIL',
  'mil': 'MIL',
  'milwaukee': 'MIL',
  'milwaukee bucks': 'MIL',
  'min': 'MIN',
  'minnesota': 'MIN',
  'minnesota timberwolves': 'MIN',
  'timberwolves': 'MIN',
  'new orleans': 'NO',
  'new orleans pelicans': 'NO',
  'no': 'NO',
  'nop': 'NO',
  'pelicans': 'NO',
  'knicks': 'NY',
  'new york': 'NY',
  'new york knicks': 'NY',
  'ny': 'NY',
  'nyk': 'NY',
  'okc': 'OKC',
  'oklahoma city': 'OKC',
  'oklahoma city thunder': 'OKC',
  'thunder': 'OKC',
  'magic': 'ORL',
  'orl': 'ORL',
  'orlando': 'ORL',
  'orlando magic': 'ORL',
  '76ers': 'PHI',
  'phi': 'PHI',
  'philadelphia': 'PHI',
  'philadelphia 76ers': 'PHI',
  'pho': 'PHX',
  'phoenix': 'PHX',
  'phoenix suns': 'PHX',
  'phx': 'PHX',
  'suns': 'PHX',
  'por': 'POR',
  'portland': 'POR',
  'portland trail blazers': 'POR',
  'trail blazers': 'POR',
  'sa': 'SA',
  'san antonio': 'SA',
  'san antonio spurs': 'SA',
  'sas': 'SA',
  'spurs': 'SA',
  'kings': 'SAC',
  'sac': 'SAC',
  'sacramento': 'SAC',
  'sacramento kings': 'SAC',
  'raptors': 'TOR',
  'tor': 'TOR',
  'toronto': 'TOR',
  'toronto raptors': 'TOR',
  'jazz': 'UTAH',
  'uta': 'UTAH',
  'utah': 'UTAH',
  'utah jazz': 'UTAH',
  'was': 'WSH',
  'washington': 'WSH',
  'washington wizards': 'WSH',
  'wizards': 'WSH',
  'wsh': 'WSH',
}

const MLB_NAME_ABBREV: Record<string, string> = {
  'ari': 'ARI',
  'arizona': 'ARI',
  'arizona diamondbacks': 'ARI',
  'az': 'ARI',
  'diamondbacks': 'ARI',
  'ath': 'ATH',
  'athletics': 'ATH',
  'athletics athletics': 'ATH',
  'oak': 'ATH',
  'atl': 'ATL',
  'atlanta': 'ATL',
  'atlanta braves': 'ATL',
  'braves': 'ATL',
  'bal': 'BAL',
  'baltimore': 'BAL',
  'baltimore orioles': 'BAL',
  'orioles': 'BAL',
  'bos': 'BOS',
  'boston': 'BOS',
  'boston red sox': 'BOS',
  'red sox': 'BOS',
  'chc': 'CHC',
  'chicago cubs': 'CHC',
  'cubs': 'CHC',
  'chicago white sox': 'CHW',
  'chw': 'CHW',
  'cws': 'CHW',
  'white sox': 'CHW',
  'cin': 'CIN',
  'cincinnati': 'CIN',
  'cincinnati reds': 'CIN',
  'reds': 'CIN',
  'cle': 'CLE',
  'cleveland': 'CLE',
  'cleveland guardians': 'CLE',
  'guardians': 'CLE',
  'col': 'COL',
  'colorado': 'COL',
  'colorado rockies': 'COL',
  'rockies': 'COL',
  'det': 'DET',
  'detroit': 'DET',
  'detroit tigers': 'DET',
  'tigers': 'DET',
  'astros': 'HOU',
  'hou': 'HOU',
  'houston': 'HOU',
  'houston astros': 'HOU',
  'kansas city': 'KC',
  'kansas city royals': 'KC',
  'kc': 'KC',
  'kcr': 'KC',
  'royals': 'KC',
  'angels': 'LAA',
  'laa': 'LAA',
  'los angeles angels': 'LAA',
  'dodgers': 'LAD',
  'lad': 'LAD',
  'los angeles dodgers': 'LAD',
  'marlins': 'MIA',
  'mia': 'MIA',
  'miami': 'MIA',
  'miami marlins': 'MIA',
  'brewers': 'MIL',
  'mil': 'MIL',
  'milwaukee': 'MIL',
  'milwaukee brewers': 'MIL',
  'min': 'MIN',
  'minnesota': 'MIN',
  'minnesota twins': 'MIN',
  'twins': 'MIN',
  'mets': 'NYM',
  'new york mets': 'NYM',
  'nym': 'NYM',
  'new york yankees': 'NYY',
  'nyy': 'NYY',
  'yankees': 'NYY',
  'phi': 'PHI',
  'philadelphia': 'PHI',
  'philadelphia phillies': 'PHI',
  'phillies': 'PHI',
  'pirates': 'PIT',
  'pit': 'PIT',
  'pittsburgh': 'PIT',
  'pittsburgh pirates': 'PIT',
  'padres': 'SD',
  'san diego': 'SD',
  'san diego padres': 'SD',
  'sd': 'SD',
  'sdp': 'SD',
  'mariners': 'SEA',
  'sea': 'SEA',
  'seattle': 'SEA',
  'seattle mariners': 'SEA',
  'giants': 'SF',
  'san francisco': 'SF',
  'san francisco giants': 'SF',
  'sf': 'SF',
  'sfg': 'SF',
  'cardinals': 'STL',
  'st louis': 'STL',
  'st louis cardinals': 'STL',
  'stl': 'STL',
  'rays': 'TB',
  'tampa bay': 'TB',
  'tampa bay rays': 'TB',
  'tb': 'TB',
  'tbr': 'TB',
  'rangers': 'TEX',
  'tex': 'TEX',
  'texas': 'TEX',
  'texas rangers': 'TEX',
  'blue jays': 'TOR',
  'tor': 'TOR',
  'toronto': 'TOR',
  'toronto blue jays': 'TOR',
  'nationals': 'WSH',
  'was': 'WSH',
  'washington': 'WSH',
  'washington nationals': 'WSH',
  'wsh': 'WSH',
}

const MLS_NAME_ABBREV: Record<string, string> = {
  'atl': 'ATL',
  'atlanta': 'ATL',
  'atlanta united fc': 'ATL',
  'atlanta united fc atlanta united fc': 'ATL',
  'atx': 'ATX',
  'austin': 'ATX',
  'austin fc': 'ATX',
  'austin fc austin fc': 'ATX',
  'chi': 'CHI',
  'chicago': 'CHI',
  'chicago fire fc': 'CHI',
  'chicago fire fc chicago fire fc': 'CHI',
  'cin': 'CIN',
  'cincinnati': 'CIN',
  'fc cincinnati': 'CIN',
  'fc cincinnati fc cincinnati': 'CIN',
  'clb': 'CLB',
  'columbus': 'CLB',
  'columbus crew': 'CLB',
  'columbus crew columbus crew': 'CLB',
  'charlotte': 'CLT',
  'charlotte fc': 'CLT',
  'charlotte fc charlotte fc': 'CLT',
  'clt': 'CLT',
  'col': 'COL',
  'colorado': 'COL',
  'colorado rapids': 'COL',
  'colorado rapids colorado rapids': 'COL',
  'dal': 'DAL',
  'dallas': 'DAL',
  'fc dallas': 'DAL',
  'fc dallas fc dallas': 'DAL',
  'd c united': 'DC',
  'd c united d c united': 'DC',
  'dc': 'DC',
  'dcu': 'DC',
  'hou': 'HOU',
  'houston': 'HOU',
  'houston dynamo fc': 'HOU',
  'houston dynamo fc houston dynamo fc': 'HOU',
  'la': 'LA',
  'la galaxy': 'LA',
  'la galaxy la galaxy': 'LA',
  'lag': 'LA',
  'lafc': 'LAFC',
  'lafc lafc': 'LAFC',
  'inter miami cf': 'MIA',
  'inter miami cf inter miami cf': 'MIA',
  'mia': 'MIA',
  'miami': 'MIA',
  'min': 'MIN',
  'minnesota': 'MIN',
  'minnesota united fc': 'MIN',
  'minnesota united fc minnesota united fc': 'MIN',
  'cf montr al': 'MTL',
  'cf montr al cf montr al': 'MTL',
  'mtl': 'MTL',
  'ne': 'NE',
  'ner': 'NE',
  'new england': 'NE',
  'new england revolution': 'NE',
  'new england revolution new england revolution': 'NE',
  'nashville': 'NSH',
  'nashville sc': 'NSH',
  'nashville sc nashville sc': 'NSH',
  'nsh': 'NSH',
  'new york city fc': 'NYC',
  'new york city fc new york city fc': 'NYC',
  'nyc': 'NYC',
  'nycfc': 'NYC',
  'orl': 'ORL',
  'orlando': 'ORL',
  'orlando city sc': 'ORL',
  'orlando city sc orlando city sc': 'ORL',
  'phi': 'PHI',
  'philadelphia': 'PHI',
  'philadelphia union': 'PHI',
  'philadelphia union philadelphia union': 'PHI',
  'por': 'POR',
  'portland': 'POR',
  'portland timbers': 'POR',
  'portland timbers portland timbers': 'POR',
  'ny': 'RBNY',
  'nyrb': 'RBNY',
  'rbny': 'RBNY',
  'red bull new york': 'RBNY',
  'red bull new york red bull new york': 'RBNY',
  'red bull ny': 'RBNY',
  'real salt lake': 'RSL',
  'real salt lake real salt lake': 'RSL',
  'rsl': 'RSL',
  'salt lake': 'RSL',
  'san diego': 'SD',
  'san diego fc': 'SD',
  'san diego fc san diego fc': 'SD',
  'sd': 'SD',
  'sea': 'SEA',
  'seattle': 'SEA',
  'seattle sounders fc': 'SEA',
  'seattle sounders fc seattle sounders fc': 'SEA',
  'san jose': 'SJ',
  'san jose earthquakes': 'SJ',
  'san jose earthquakes san jose earthquakes': 'SJ',
  'sj': 'SJ',
  'kansas city': 'SKC',
  'skc': 'SKC',
  'sporting kansas city': 'SKC',
  'sporting kansas city sporting kansas city': 'SKC',
  'st louis': 'STL',
  'st louis city sc': 'STL',
  'st louis city sc st louis city sc': 'STL',
  'stl': 'STL',
  'tor': 'TOR',
  'toronto': 'TOR',
  'toronto fc': 'TOR',
  'toronto fc toronto fc': 'TOR',
  'van': 'VAN',
  'vancouver': 'VAN',
  'vancouver whitecaps': 'VAN',
  'vancouver whitecaps vancouver whitecaps': 'VAN',
}

function normTeamKey(value: string): string {
  return String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

export function majorLeagueNameAbbrevMap(sportKey: string): Record<string, string> | null {
  const sk = String(sportKey || '')
  if (sk.includes('icehockey_nhl')) return NHL_NAME_ABBREV
  if (sk.includes('basketball_nba')) return NBA_NAME_ABBREV
  if (sk.includes('baseball_mlb')) return MLB_NAME_ABBREV
  if (sk.includes('soccer_usa_mls')) return MLS_NAME_ABBREV
  return null
}

export function majorLeagueAbbrevFromName(sportKey: string, name: string, fallback = ''): string {
  const map = majorLeagueNameAbbrevMap(sportKey)
  const raw = String(name || '').trim()
  if (!map || !raw) return String(fallback || '').trim().toUpperCase()
  const full = normTeamKey(raw)
  if (map[full]) return map[full]
  const parts = full.split(' ').filter(Boolean)
  for (let i = 1; i < parts.length; i++) {
    const tail = parts.slice(i).join(' ')
    if (map[tail]) return map[tail]
  }
  const fb = String(fallback || '').trim()
  if (fb && map[normTeamKey(fb)]) return map[normTeamKey(fb)]
  return fb.toUpperCase()
}
