-- Poker catalog GPS match: rooms added for multi-state expansion (safe re-run).
insert into public.casinos (name, source, city, state, country, lat, lng)
values
  ('Commerce Casino',              'seed', 'Commerce',     'California', 'United States', 34.0822,  -118.1526),
  ('Bicycle Casino',               'seed', 'Bell Gardens', 'California', 'United States', 33.9679,  -118.1650),
  ('Hollywood Park Casino',        'seed', 'Inglewood',    'California', 'United States', 33.9828,  -118.3442),
  ('Seminole Hard Rock Hollywood', 'seed', 'Hollywood',    'Florida',    'United States', 26.0515,  -80.2120),
  ('Lone Butte Casino',            'seed', 'Chandler',     'Arizona',    'United States', 33.3068,  -111.9445),
  ('Desert Diamond West Valley',   'seed', 'Glendale',     'Arizona',    'United States', 33.5234,  -112.2598),
  ('Rivers Casino Des Plaines',    'seed', 'Des Plaines',  'Illinois',   'United States', 42.0320,   -87.8876),
  ('Grand Victoria Casino',        'seed', 'Elgin',        'Illinois',   'United States', 42.0372,   -88.3234),
  ('Running Aces Casino',          'seed', 'Columbus',     'Minnesota',  'United States', 45.2683,   -93.0558),
  ('The Orleans',                'seed', 'Las Vegas',    'Nevada',     'United States', 36.1026,  -115.2034),
  ('Caesars Southern Indiana',   'seed', 'Elizabeth',    'Indiana',    'United States', 38.8701,   -84.9267),
  ('Horseshoe Indianapolis',     'seed', 'Shelbyville',  'Indiana',    'United States', 39.5519,   -85.7923),
  ('Potawatomi Casino Hotel',    'seed', 'Milwaukee',    'Wisconsin',  'United States', 43.0339,   -87.9508),
  ('Ameristar East Chicago',     'seed', 'East Chicago', 'Indiana',    'United States', 41.6558,   -87.4542),
  ('Ameristar Casino St. Charles','seed', 'St. Charles',  'Missouri',   'United States', 38.7792,   -90.5154),
  ('Riverside Casino',           'seed', 'Riverside',    'Iowa',       'United States', 41.4683,   -91.5879),
  ('Grand Falls Casino',         'seed', 'Larchwood',    'Iowa',       'United States', 43.4538,   -96.4367),
  ('Sycuan Casino Resort',         'seed', 'El Cajon',     'California', 'United States', 32.7881,  -116.9354),
  ('JACK Cleveland Casino',      'seed', 'Cleveland',    'Ohio',       'United States', 41.4993,   -81.6937),
  ('Bally''s Black Hawk Casino',  'seed', 'Black Hawk',   'Colorado',   'United States', 39.7979,  -105.4922),
  -- MTTDB unmapped venues (US + international poker rooms)
  ('Stones Gambling Hall',              'seed', 'Citrus Heights',  'California',     'United States', 38.7077,  -121.2812),
  ('Chinook Winds Casino Resort',       'seed', 'Lincoln City',    'Oregon',         'United States', 44.9980,  -124.0094),
  ('Atlantis Casino Resort',            'seed', 'Reno',            'Nevada',         'United States', 39.5381,  -119.8147),
  ('Red Rock Casino Resort & Spa',      'seed', 'Las Vegas',       'Nevada',         'United States', 36.1577,  -115.3364),
  ('Bally''s Twin River Lincoln Casino','seed', 'Lincoln',         'Rhode Island',   'United States', 41.9369,   -71.4597),
  ('King''s Resort',                    'seed', 'Rozvadov',        '',               'Czech Republic', 49.6906,   12.5622),
  ('Bestbet St. Augustine',             'seed', 'St. Augustine',   'Florida',        'United States', 29.8576,   -81.3247),
  ('The OG Clubhouse',                  'seed', 'Oak Grove',       'Kentucky',       'United States', 36.6676,   -87.4389),
  ('Royal Casino JOA Cannes',           'seed', 'Cannes',          '',               'France',         43.5508,    7.0242),
  ('Lodge Card Club',                   'seed', 'Austin',          'Texas',          'United States', 30.1989,   -97.7656),
  ('Lilac Club Casino',                 'seed', 'Rochester',       'New York',       'United States', 43.1558,   -77.5889),
  ('TGT Poker & Racebook',              'seed', 'Tampa',           'Florida',        'United States', 27.9236,   -82.5125),
  ('Portomaso Casino',                  'seed', 'St Julians',      '',               'Malta',          35.9228,   14.4897),
  ('Grand Sierra Resort and Casino',    'seed', 'Reno',            'Nevada',         'United States', 39.6766,  -119.7752),
  ('Grand Casino Hotel & Resort',       'seed', 'Shawnee',         'Oklahoma',       'United States', 35.3708,   -96.9528),
  ('Bestbet Orange Park',               'seed', 'Orange Park',     'Florida',        'United States', 30.1664,   -81.7064),
  ('Orange City Racing & Card Club',    'seed', 'Orange City',     'Florida',        'United States', 28.9489,   -81.2986),
  ('Dragonara Casino',                  'seed', 'St Julians',      '',               'Malta',          35.9264,   14.4947),
  ('Bestbet Jacksonville',               'seed', 'Jacksonville',    'Florida',        'United States', 30.1889,   -81.6422),
  ('Pearl River Resort',                'seed', 'Choctaw',         'Mississippi',    'United States', 32.8744,   -89.1533),
  ('Pure Casino Yellowhead',            'seed', 'Edmonton',        'Alberta',        'Canada',         53.5472,  -113.5764),
  ('Terre Haute Casino',                'seed', 'Terre Haute',     'Indiana',        'United States', 39.4336,   -87.4128),
  ('Casino Schenefeld',                 'seed', 'Schenefeld',      '',               'Germany',        53.6021,    9.8378)
on conflict (lower(name)) do update set lat = excluded.lat, lng = excluded.lng;
