-- Seed Local Intel data (cities + casinos)
-- Generated by scripts/generate-local-intel-seed-sql.mjs
-- Safe to re-run: uses WHERE NOT EXISTS checks (no deletes).

begin;

-- Cities
insert into public.cities (name, region)
select 'Las Vegas', 'NV'
where not exists (
  select 1 from public.cities
  where lower(name) = lower('Las Vegas')
    and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
);

insert into public.cities (name, region)
select 'Reno', 'NV'
where not exists (
  select 1 from public.cities
  where lower(name) = lower('Reno')
    and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
);

-- Casinos
insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Aliante Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Aliante Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Aria' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Aria')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Aria Resort & Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Aria Resort & Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Arizona Charlies Decatur' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Arizona Charlies Decatur')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Bellagio' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Bellagio')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Best Western Plus Casino Royale' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Best Western Plus Casino Royale')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Binion''s Gambling Hall and Hotel' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Binion''s Gambling Hall and Hotel')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Bonanza Lounge & Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Bonanza Lounge & Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Caesars Palace' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Caesars Palace')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Caesars Palace Complex' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Caesars Palace Complex')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Caesars Palace Poker Room' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Caesars Palace Poker Room')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Cannery Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Cannery Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Circus Circus Las Vegas' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Circus Circus Las Vegas')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Club Fortune Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Club Fortune Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Dotty''s' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Dotty''s')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Dotty''s Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Dotty''s Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'El Cortez Hotel & Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('El Cortez Hotel & Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Ellis Island Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Ellis Island Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Emerald Island Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Emerald Island Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Encore Beach Club' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Encore Beach Club')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Encore Casino at Wynn' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Encore Casino at Wynn')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Excalibur Hotel & Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Excalibur Hotel & Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Flamingo Las Vegas' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Flamingo Las Vegas')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Fremont Hotel & Casino Las Vegas' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Fremont Hotel & Casino Las Vegas')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Gold Coast Hotel & Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Gold Coast Hotel & Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Gold Spike' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Gold Spike')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Hard Rock Las Vegas' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Hard Rock Las Vegas')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Harrah''s Showroom' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Harrah''s Showroom')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Horseshoe Las Vegas' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Horseshoe Las Vegas')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Hotel MGM Grand Las Vegas' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Hotel MGM Grand Las Vegas')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Jackpot Joanie''s' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Jackpot Joanie''s')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Jackpot Joanie''s Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Jackpot Joanie''s Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Jerry''s Nugget Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Jerry''s Nugget Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Jokers Wild Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Jokers Wild Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Just Play' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Just Play')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'La Villita Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('La Villita Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Longhorn Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Longhorn Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Lucky Club Hotel & Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Lucky Club Hotel & Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Luxor Las Vegas' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Luxor Las Vegas')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Mandalay Bay' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Mandalay Bay')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'MGM Grand' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('MGM Grand')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Miz Lola''s Spirits & Gaming' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Miz Lola''s Spirits & Gaming')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'New York New York Hotel and Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('New York New York Hotel and Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'NoMad High Limit Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('NoMad High Limit Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Palms' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Palms')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Paris Las Vegas' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Paris Las Vegas')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Park MGM' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Park MGM')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Pat''s Pub' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Pat''s Pub')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Planet Hollywood' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Planet Hollywood')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'PT''s' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('PT''s')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Railroad Pass Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Railroad Pass Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Rainbow Club Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Rainbow Club Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Rampart Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Rampart Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Red Dragon Gaming & Spirits' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Red Dragon Gaming & Spirits')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Resorts World Las Vegas' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Resorts World Las Vegas')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Rio All Suite Hotel and Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Rio All Suite Hotel and Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Sahara Las Vegas Hotel & Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Sahara Las Vegas Hotel & Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Skyline Hotel and Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Skyline Hotel and Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'South Point' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('South Point')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'South Point Hotel, Casino & Spa' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('South Point Hotel, Casino & Spa')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Stage Door Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Stage Door Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Suncoast Hotel and Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Suncoast Hotel and Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Sunset Station' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Sunset Station')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'The LINQ' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('The LINQ')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'The LINQ Hotel + Experience' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('The LINQ Hotel + Experience')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'The M Resort' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('The M Resort')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'The Orleans Hotel & Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('The Orleans Hotel & Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'The Palazzo' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('The Palazzo')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'The Pass Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('The Pass Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'The Strat' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('The Strat')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'The Venetian Las Vegas' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('The Venetian Las Vegas')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Tix4Tonight - Slots A Fun' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Tix4Tonight - Slots A Fun')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Treasure Island' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Treasure Island')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Treasure Island Hotel and Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Treasure Island Hotel and Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Tuscany Suites & Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Tuscany Suites & Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Wildfire' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Wildfire')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Wildfire Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Wildfire Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Las Vegas')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Wynn Las Vegas Casino' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Las Vegas')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Wynn Las Vegas Casino')
);

insert into public.casinos (city_id, name)
select
  (
    select id from public.cities
    where lower(name) = lower('Reno')
      and lower(coalesce(region, '')) = lower(coalesce('NV', ''))
    limit 1
  ) as city_id,
  'Peppermill Reno' as name
where not exists (
  select 1 from public.casinos cs
  join public.cities ct on ct.id = cs.city_id
  where lower(ct.name) = lower('Reno')
    and lower(coalesce(ct.region, '')) = lower(coalesce('NV', ''))
    and lower(cs.name) = lower('Peppermill Reno')
);

commit;
